const GENECODE_CONFIG = {
  whatsappNumber: "91XXXXXXXXXX",
  instagramHandle: "@genecode",
  dropName: "DROP 01",
  tagline: "WEAR YOUR CODE",
  aboutText:
    "Genecode is a men's shirt label built on sharp silhouettes and quiet confidence. Drop 01 is six pieces—released on a rhythm, not a noise. Replace this with your real story when you're ready.",

  shirts: [
    {
      id: "GC-01",
      name: "Shirt One",
      tagline: "First move. Clean line.",
      price: "₹999",
      sizes: ["S", "M", "L", "XL"],
      image: "assets/shirts/shirt-01.jpg",
      revealDate: null,
    },
    {
      id: "GC-02",
      name: "Shirt Two",
      tagline: "Second position. Same precision.",
      price: "₹999",
      sizes: ["S", "M", "L", "XL"],
      image: "assets/shirts/shirt-02.jpg",
      revealDate: null,
    },
    {
      id: "GC-03",
      name: null,
      tagline: null,
      price: null,
      sizes: [],
      image: "assets/shirts/shirt-03.jpg",
      revealDate: "2026-07-10T10:00:00",
    },
    {
      id: "GC-04",
      name: null,
      tagline: null,
      price: null,
      sizes: [],
      image: "assets/shirts/shirt-04.jpg",
      revealDate: "2026-07-12T10:00:00",
    },
    {
      id: "GC-05",
      name: null,
      tagline: null,
      price: null,
      sizes: [],
      image: "assets/shirts/shirt-05.jpg",
      revealDate: "2026-07-14T10:00:00",
    },
    {
      id: "GC-06",
      name: null,
      tagline: null,
      price: null,
      sizes: [],
      image: "assets/shirts/shirt-06.jpg",
      revealDate: "2026-07-16T10:00:00",
    },
  ],
};
